name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: wangyucode/sftp-upload-action@v1.3.2
        with:
          host: ssh.strato.de
          username: sftp_ulrichalt@neu.tanzkreis-sulzbach.com
          localdir: _dist
          remoteDir: /
          password: {{ secrets.STRATO_PASSWORD }}


